version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app # This line mounts the current directory (.) on the host to /app inside the container. Any changes made in the current directory are reflected inside the container.
      - /app/node_modules # This line creates a Docker volume for /app/node_modules. This is useful when you want to preserve the node_modules folder but don't want to include it in your build context.

  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - app
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

