# Use the official Node.js 20 image as the base image
FROM node:20-buster

# Set the working directory inside the container
WORKDIR /app

# Install lsb-release and openssl for mongo-memory-server
RUN apt-get update && apt-get install -y lsb-release openssl libcurl4


# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire backend folder to the working directory
COPY . .

# Run the tests
CMD ["npm", "test"]
